"""add transaction confidence

Revision ID: 753d6749b7ee
Revises: baf1f34ebd61
Create Date: 2026-09-13 21:13:33.047910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753d6749b7ee'
down_revision: Union[str, Sequence[str], None] = 'baf1f34ebd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=4, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'confidence',
               existing_type=sa.Numeric(precision=4, scale=3),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
