"""add transaction fingerprint

Revision ID: 95fce11dc132
Revises: 382286d14cf5
Create Date: 2026-09-14 17:51:34.852492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fce11dc132'
down_revision: Union[str, Sequence[str], None] = '382286d14cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'fingerprint')
    # ### end Alembic commands ###
