"""add transaction ingestion fields

Revision ID: a6c58bcebdf4
Revises: 517b18632d31
Create Date: 2026-08-31 21:45:18.360188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c58bcebdf4'
down_revision: Union[str, Sequence[str], None] = '517b18632d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions',sa.Column('status',sa.String(length=20),nullable=False,server_default="completed"))
    op.add_column('transactions', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('source_app', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'source_app')
    op.drop_column('transactions', 'raw_text')
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###
